# Generated by Django 5.1.3 on 2024-11-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='date_of_show',
            new_name='date',
        ),
    ]
