# Generated by Django 4.2.20 on 2025-04-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_date_of_show_concert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, default='concert_images/default.jpg', null=True, upload_to='concert_images/'),
        ),
    ]
